name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - run: dotnet pack .\LogicBuilder.OData.EFCore\LogicBuilder.OData.EFCore.csproj -c Release -o .\artifacts --no-build
    - run: dotnet pack .\LogicBuilder.AspNet.OData.EF6\LogicBuilder.AspNet.OData.EF6.csproj -c Release -o .\artifacts --no-build
    - run: dotnet pack .\LogicBuilder.AspNetCore.OData.EF6\LogicBuilder.AspNetCore.OData.EF6.csproj -c Release -o .\artifacts --no-build
    - name: Set Version Number
      run: echo '::set-env name=VERSION_NUMBER::2.0.1-preview03'
    - run dotnet nuget push ".\artifacts\LogicBuilder.OData.EFCore.{$Env:VERSION_NUMBER}.nupkg"  --source $Env:NUGET_URL --api-key $Env:NUGET_API_KEY
    - run dotnet nuget push ".\artifacts\LogicBuilder.AspNet.OData.EF6.{$Env:VERSION_NUMBER}.nupkg"  --source $Env:NUGET_URL --api-key $Env:NUGET_API_KEY
    - run dotnet nuget push ".\artifacts\LogicBuilder.AspNetCore.OData.EF6.{$Env:VERSION_NUMBER}.nupkg"  --source $Env:NUGET_URL --api-key $Env:NUGET_API_KEY
#    - name: Push to NuGet
#      env:
#        NUGET_URL: https://api.nuget.org/v3/index.json
#        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
#      run: ./Push.ps1
#      shell: pwsh
