name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/blaised/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Variables
      run: |
        echo '::set-env name=VERSION_NUMBER::2.0.1-preview09'
        echo '::set-env name=NUGET_URL::https://api.nuget.org/v3/index.json'
        echo '::set-env name=NUGET_API_KEY::${{ secrets.NUGET_API_KEY }}'
        echo '::set-env name=REPO::${{ github.repository }}'
        echo '::set-env name=REPO_OWNER::${{ github.repository_owner }}'
        echo '::set-env name=TAG_NO::${{ steps.vars.outputs.tag }}'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.AspNet.OData'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.AspNetCore.OData'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.OData.EFCore'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.AspNet.OData.EF6'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.AspNetCore.OData.EF6'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh
