name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/blaised/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Variables
      run: |
        echo "VERSION_NUMBER=2.0.1-preview09" >> $GITHUB_ENV
        echo "NUGET_URL=https://api.nuget.org/v3/index.json" >> $GITHUB_ENV
        echo "NUGET_API_KEY=${{ secrets.NUGET_API_KEY }}" >> $GITHUB_ENV
        echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
        echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "TAG_NO=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV
#        echo '::set-env name=VERSION_NUMBER::2.0.1-preview09'
#        echo '::set-env name=NUGET_URL::https://api.nuget.org/v3/index.json'
#        echo '::set-env name=NUGET_API_KEY::${{ secrets.NUGET_API_KEY }}'
#        echo '::set-env name=REPO::${{ github.repository }}'
#        echo '::set-env name=REPO_OWNER::${{ github.repository_owner }}'
#        echo '::set-env name=TAG_NO::${{ steps.vars.outputs.tag }}'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack and push LogicBuilder.AspNet.OData
      env:
        PROJECT_NAME: LogicBuilder.AspNet.OData
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - name: Pack and push LogicBuilder.AspNetCore.OData
      env:
        PROJECT_NAME: LogicBuilder.AspNetCore.OData
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - name: Pack and push LogicBuilder.OData.EFCore
      env:
        PROJECT_NAME: LogicBuilder.OData.EFCore
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - name: Pack and push LogicBuilder.AspNet.OData.EF6
      env:
        PROJECT_NAME: LogicBuilder.AspNet.OData.EF6
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - name: Pack and push LogicBuilder.AspNetCore.OData.EF6
      env:
        PROJECT_NAME: LogicBuilder.AspNetCore.OData.EF6
      run: ./Release_Pack_Push.ps1
      shell: pwsh
