name: Echo


on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Echo
      env:
        SOME_KEY: "ABCD"
      run: echo "here" + ${SOME_KEY}
    - name: Echo
      run: echo "here " + ${SOME_KEY}
